sudo: false

language: java

jdk: oraclejdk8

notifications:
  irc: "chat.freenode.net#seedstack-dev"

cache:
  directories: "$HOME/.m2/repository"

script: travis_wait mvn -q -U clean install

after_success: if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = master ]; then chmod +x deploy-javadoc.sh && ./deploy-javadoc.sh; fi
