sudo: false

language: java

jdk: oraclejdk8

notifications:
  irc: "chat.freenode.net#seedstack-dev"

cache:
  directories: "$HOME/.m2/repository"

install: rm ~/.m2/settings.xml

script:
  - mvn -U -Psnapshots clean install
  - if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = master ]; then chmod +x deploy-javadoc.sh && ./deploy-javadoc.sh; fi
